class MTCError(Exception): ...
class ConfigError(MTCError): ...
class ShapeError(MTCError): ...
class FairnessError(MTCError): ...
class CalibrationError(MTCError): ...
class StackelbergError(MTCError): ...
class TransferError(MTCError): ...
